# Generated by Django 6.0.1 on 2026-01-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_hero_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='category',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.ManyToManyField(to='support_hero_api.category'),
        ),
    ]
